header = "preferences"
workspace = "workspace1"

[FileSystem]
workspace_root = "D:/Projects/Visual Studio/Quasar/Quasar/ex"

[Easel.Canvas.Checkerboard]
checker1 = [0.2, 0.3, 0.3, 0.5]
checker2 = [0.16, 0.2, 0.2, 0.5]
checker_size = [16, 16]

[Easel.Gridlines]
min_initial_image_window_proportion = 3.0
